### ISSUE TITLE
Weird scrolling issue

### ISSUE THREAD

**Issue by FlysoftBeta** [Copay/caraoke-plasmoid#3]
[video](https://github.com/Copay/caraoke-plasmoid/assets/49718840/acc2c42e-5381-4225-92d7-70455c27f29d)

Track: [Revive - LIONE](https://open.spotify.com/track/4Bb53fsDAero14LpAbsmft) 1:12 
Lyric: `Wherever you may go`

**Comment by Sinofine** [comment]
Reproducible on my machine.

There is a fix scheduled in the coming days.

**Comment by Sinofine** [comment]
I've fixed that, and commits should be pushed soon. 

Here the root of the problem is described as follows:
- If you substitute a `RowLayer` and immediately query its width, the result is the old one, which results in the weird scroll offset. Solution: use `TextMetrics`.
- If you use some `SmoothedAnimation`, setting its `duration` but not setting its `velocity`, the animation's speed would be the faster one. Solution: disable `velocity`.
